cqa/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile_view, name='profile'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cqa/', include('cqa.urls')),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from cqa.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls, name='django-admin'),
    path('cqa/', include('cqa.urls')),
    path('posts/', include('posts.urls')),
    path('search/', include('search.urls')),
]

search/urls.py
from django.urls import path
from .views import search_view, search_results_view

urlpatterns = [
    path('', search_view, name = 'search_view'),
    path('results/<str:search>', search_results_view.as_view(), name = 'search_results'),
]

search/models.py
from django.db import models

# Uses all the models defined in cqa.models
from cqa.models import *

search/forms.py
from django import forms
from setup.tags_to_json import choices

class SearchForm(forms.Form):
    search = forms.CharField(label='Search', max_length=100)

search/views.py
from django.shortcuts import render

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import *
from cqa.models import *
from search.forms import SearchForm
from django.shortcuts import redirect
from django.http import HttpResponse
from django.db.models import Q
# Create your views here.
def search_view(request):
    if(request.method == 'POST'):
        form = SearchForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data['search']
            return redirect('search_results', search = search)

    form = SearchForm()
    global context
    context["form"] = form
    print(context["users"][1])
    return render(request, "search/search_view.html", context)

class search_results_view(ListView):
    model = Posts
    template_name = 'search/search_results.html'
    paginate_by = 10
    ordering = ['-answer_count']
    context_object_name = 'posts'
    
    def get_queryset(self):
        search = self.kwargs['search']
        # try user 200302
        if(search[0] == ':'):
            search = search[1:]
            user_id = search.split(' ')[0]
            q = Posts.objects.filter(owner_user_id = int(user_id))
            return q
        if(search[0] == '#'):
            tags = search.split(',')
            tags = [ '<' + tag[1:].strip() + '>' for tag in tags ]
            # string =''.join(tags)
            # for tag in tags:
            #     q = Posts.objects.filter(Q(tags__icontains = string))
            # return q
            string = tags[0]
            q = Posts.objects.filter(tags__icontains = string)
            for tag in tags:
                q = q.union(Posts.objects.filter(tags__icontains = tag))
            return q
        else:
            return Posts.objects.filter(Q(title__icontains = search) | Q(body__icontains = search))
        
        
    

search/templates/search/search_bar_snippet.html
<!-- <form id="form", method="GET"> 
    <input type="search" id="query" name="q" placeholder="Search...">
    <button>Search</button>
</form> -->

<form action="{% url 'search_view' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
     <!-- this renders with id = id_name  -->
    <input type="submit">
    <script>
    $( function() {
        var tags =[ 
        {% for tag in tags %} 
        "{{tag}}", 
        {% endfor %} 
        ];

        var users =[
        {% for user in users%}
        "{{user}}",
        {% endfor %}
        ];

        net = tags.concat(users);

        $( "#id_search" ).autocomplete({
            source: net,
            minLength: 1,
        });
} );
</script>
    </form>
</form>

search/templates/search/search_results.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<div class="d-flex align-items-center justify-content-center">
    <h1>Posts</h1>
</div>
<div class="d-flex align-items-center justify-content-center">
    <ul>
        {% for post in posts %}
            <li> 
                {% include 'snippets/post_snippet.html'%}
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

search/templates/search/search_view.html
{% extends 'base.html' %}

{% block content %}

<!-- The search bar -->
{% include 'snippets/search_bar_snippet.html' %}

{% endblock content%}