cqa/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile_view, name='profile'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cqa/', include('cqa.urls')),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from cqa.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls, name='django-admin'),
    path('cqa/', include('cqa.urls')),
    path('posts/', include('posts.urls')),
    path('search/', include('search.urls')),
]

posts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('<int:post_id>/', detail_post, name='detail_post'),
    path('create/', create_post, name='create_post'),
    path('edit/<int:post_id>/', edit_post, name='edit_post'),
    path('answer/<int:post_id>/', answer_post, name='answer_post'),
]

posts/models.py
from django.db import models

# Create your models here.

from cqa.models import *


# class Posts(models.Model):
#     owner_user_id = models.IntegerField(blank=True, null=True)
#     last_editor_user_id = models.IntegerField(blank=True, null=True)
#     post_type_id = models.SmallIntegerField()
#     accepted_answer_id = models.IntegerField(blank=True, null=True)
#     score = models.IntegerField()
#     parent_id = models.IntegerField(blank=True, null=True)
#     view_count = models.IntegerField(blank=True, null=True)
#     answer_count = models.IntegerField(blank=True, null=True)
#     comment_count = models.IntegerField(blank=True, null=True)
#     owner_display_name = models.CharField(max_length=64, blank=True, null=True)
#     last_editor_display_name = models.CharField(max_length=64, blank=True, null=True)
#     title = models.CharField(max_length=512, blank=True, null=True)
#     tags = models.CharField(max_length=512, blank=True, null=True)
#     content_license = models.CharField(max_length=64)
#     body = models.TextField(blank=True, null=True)
#     favorite_count = models.IntegerField(blank=True, null=True)
#     creation_date = models.DateTimeField()
#     community_owned_date = models.DateTimeField(blank=True, null=True)
#     closed_date = models.DateTimeField(blank=True, null=True)
#     last_edit_date = models.DateTimeField(blank=True, null=True)
#     last_activity_date = models.DateTimeField(blank=True, null=True)

posts/forms.py
from django import forms
from setup.tags_to_json import choices

class CreatePost(forms.Form):
    title = forms.CharField(label='Title', max_length=100)
    body = forms.CharField(widget=forms.Textarea)
    tags = forms.CharField(label='Tags', max_length=100)

class EditPost(forms.Form):
    title = forms.CharField(label='Title', max_length=100)
    body = forms.CharField(widget=forms.Textarea)
    tags = forms.CharField(label='Tags', max_length=100)

    def __init__(self, post, *args, **kwargs):
        super(EditPost, self).__init__(*args, **kwargs)
        self.fields['title']. initial = post.title
        self.fields['body']. initial = post.body

class AnswerPost(forms.Form):
    body = forms.CharField(widget=forms.Textarea)

posts/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import *
from cqa.models import *
from posts.forms import CreatePost, EditPost, AnswerPost
from django.shortcuts import redirect
from django.http import HttpResponse
    
def home(request):
    posts = Posts.objects.filter().exclude(title=None)[0:10]
    context = {'posts': posts}
    return render(request, 'posts/home.html', context)

def detail_post(request, post_id):
    post = Posts.objects.filter(id=post_id)[0]
    answers = Posts.objects.filter(parent_id=post_id)
    user = CustomUser.objects.filter(id = post.owner_user_id)
    if user.count() == 0:
        username = ''
    else:
        username = user[0].username
    context = {
        'post': post,
        'answers': answers,
        'username': username
    }
    return render(request, 'posts/detail_post.html', context)
    pass

# class detail_post(DetailView):
#     template_name = 'posts/detail_post.html'
#     model = Posts
#     ordering = ['-creation_date']
#     context_object_name = 'post'
    
#     def get_context_data(self, *args, **kwargs):
#         qs = super(detail_post, self).get_context_data(*args, **kwargs)
#         # qs['user'] = "hallo"
#         # print(type(self.request.user.display_name))
#         return qs


def create_post(request):
    global context
    if not request.user.is_authenticated:
        redirect('home')

    if request.method == 'POST':
        form = CreatePost(request.POST)
        user = request.user
        if form.is_valid():
            object = Posts()
            object.owner_user_id = user.id
            object.post_type_id = '1'
            object.answer_count = 0
            object.comment_count = 0
            object.owner_display_name = user.display_name
            object.title = form.cleaned_data['title']
            object.tags = form.cleaned_data['tags']
            tags = form.cleaned_data['tags'].split(',')
            tags = [tag[1:] for tag in tags]
            tags = [ '<' + tag.strip() + '>' for tag in tags ]
            object.tags = ''.join(tags)
            object.content_license='CC BY SA 2.5'  # dummy value
            object.body = form.cleaned_data['body']
            # TO DO: insert the corresponding fields into the tags table as well
            object.score = 0 # dummy
            
            object.save()
            # redirect to a detail view of the post you just created instead
            return redirect('profile')


    new_post = CreatePost()
    context["form"] = new_post
    return render(request, 'posts/creation_form.html', context)

def edit_post(request, post_id):
    global context
    if not request.user.is_authenticated:
        redirect('home')

    curr_post = Posts.objects.get(id=post_id)
    user = request.user

    # Checking if the user is the owner of the post
    if curr_post.owner_user_id != user.account_id:
        redirect('home')

    if request.method == 'POST':
        form = EditPost(curr_post, request.POST)
        if form.is_valid():
            print('Hello')
            curr_post.title = form.cleaned_data['title']
            curr_post.body = form.cleaned_data['body']
            # curr_post.tags = form.cleaned_data['tags']
            tags = form.cleaned_data['tags'].split(',')
            tags = [ '<' + tag.strip() + '>' for tag in tags ]
            curr_post.tags = ''.join(tags)
            curr_post.save()
            return redirect('home')
        else:
            print('bonk')
            print(form.errors)
            print(form.non_field_errors)
    
    form = EditPost(curr_post)
    context["form"] = form
    context["post_id"] = post_id
    # context = {'form': form, 'post_id': post_id}
    return render(request, 'posts/edit_form.html', context)


def answer_post(request, post_id):

    if not request.user.is_authenticated:
        redirect('home')
    
    curr_post = Posts.objects.get(id = post_id) 
    user = request.user

    if request.method == 'POST':
        form = AnswerPost(request.POST, curr_post)
        if form.is_valid():
            object = Posts()

            object.owner_user_id = user.id
            object.post_type_id = '2'
            object.answer_count = 0
            if not curr_post.answer_count:
                curr_post.answer_count = 0
            curr_post.answer_count += 1

            object.comment_count = 0
            object.tags = curr_post.tags
            object.content_license = curr_post.content_license
            object.parent_id = curr_post.pk
            object.title = "[Answer]" + curr_post.title
            object.body = form.cleaned_data['body']

            object.score = 0

            object.save()
            return redirect('detail_post', post_id=object.pk)

    form = AnswerPost()
    context = {'form': form, 'post_id': post_id,}
    return render(request, 'posts/answer_form.html', context)

posts/templates/posts/answer_form.html
{% extends 'base.html' %}

{% block content %}
<br><br>
<div class="d-flex align-items-center justify-content-center"> 
    <h1>Answer to Post #{{post_id}}</h1>
</div>
<!-- <div class="mx-auto col-10 col-md-8 col-lg-6 my-auto">
<form action="{% url 'answer_post' post_id=post_id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
    </form>
</div> -->

<div class="d-flex align-items-center justify-content-center"> 
    <form action="{% url 'answer_post' post_id=post_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
</div>

{% endblock %}

posts/templates/posts/creation_form.html
{% extends 'base.html' %}

{% block content %}

<!-- <div class="mx-auto col-10 col-md-8 col-lg-6 my-auto">
<form action="{% url 'create_post' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
    <script>
        $( function() {
            var tags =[ 
            {% for tag in tags %} 
            "{{tag}}", 
            {% endfor %} 
            ];
            $( "#id_tags" ).autocomplete({
                source: tags,
                minLength: 1,
            });
    } );
    </script>
    </form>
</div> -->
<br><br>
<div class="d-flex align-items-center justify-content-center"> 
    <h1>Create new post</h1>
</div>
<hr style = "height:2px;border-width:0;color:black ;background-color: black; margin-left:65px;margin-right:65px">
<div  class="d-flex align-items-center justify-content-center" style="margin: 20px;">
    <form action="{% url 'create_post' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
        <script>
            $( function() {
                var tags =[ 
                {% for tag in tags %} 
                "{{tag}}", 
                {% endfor %} 
                ];
                $( "#id_tags" ).autocomplete({
                    source: tags,
                    minLength: 1,
                });
        } );
        </script>
        </form>
</div>
{% endblock %}

posts/templates/posts/detail_post.html
{% extends 'base.html' %}

{% block content %}
<br><br/>
<div class="d-flex align-items-center justify-content-center">
    {% if post.title is None %}
        <h1>Untitled Post</h1>
    {% else %}
        <h1>{{post.title}}</h1>
    {% endif%}
</div>

<div class="d-flex align-items-center justify-content-center">
    <!-- Posted By: User {{post.owner_user_id}} -->
    <a href="{%url 'answer_post' post_id=post.id%}" style = 'color:rgb(235, 67, 196); margin:2px'>(Answer)</a>
    {% if post.owner_user_id == request.user.account_id %}
    <a href="{%url 'edit_post' post_id=post.id%}" style = 'color:rgb(219, 195, 10); margin:2px'>(Edit)</a>
    {% endif %}
</div>
<div class="d-flex align-items-center justify-content-center">Tags: {{post.tags}}</div>
<div class="d-flex align-items-center justify-content-center">
    Post By: {{username}} (User # {{post.owner_user_id}})
</div>

    
<div class="align-items-center justify-content-center" style="margin-left:20px; margin-right:20px">
    <br><br/>
    {{ post.body | safe }} 
    <br><br/>
    <h3>{{post.user}}</h3>
</div>


    {% if answers.count > 0 %}
    <div class="d-flex align-items-center justify-content-center">
        <h2>Answers:</h2>
    </div>
    <div class="d-flex align-items-center justify-content-center">
        <ul>
        {% for post in answers %}
            <li>      
                {% include 'snippets/post_snippet.html'%}
            </li>
        {% endfor %}
        </ul>
    {% endif %}
    </div>
    
{% endblock %}

posts/templates/posts/edit_form.html
{% extends 'base.html' %}

{% block content %}
 <!-- <div class="mx-auto col-10 col-md-8 col-lg-6 my-auto">
<form action="{%url 'edit_post' post_id=post_id%} " method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
    <script>
        $( function() {
            var tags =[ 
            {% for tag in tags %} 
            "{{tag}}", 
            {% endfor %} 
            ];
            $( "#id_tags" ).autocomplete({
                source: tags,
                minLength: 1,
            });
    } );
    </script>
</form> 
</div> -->

<br><br>
<div class="d-flex align-items-center justify-content-center"> 
    <h1>Edit post #{{post_id}}</h1>
</div>
<hr style = "height:2px;border-width:0;color:black ;background-color: black; margin-left:65px;margin-right:65px">
<div  class="d-flex align-items-center justify-content-center" style="margin: 20px;">
    <form action="{%url 'edit_post' post_id=post_id%} " method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
        <script>
            $( function() {
                var tags =[ 
                {% for tag in tags %} 
                "{{tag}}", 
                {% endfor %} 
                ];
                $( "#id_tags" ).autocomplete({
                    source: tags,
                    minLength: 1,
                });
        } );
        </script>
    </form> 
</div>

{% endblock %}

posts/templates/posts/home.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<div class="d-flex align-items-center justify-content-center">
    <h1>Posts</h1>
</div>
<div class="d-flex align-items-center justify-content-center">
    <ul>
        {% for post in posts %}
        <li>      
            {% include 'snippets/post_snippet.html'%}
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

posts/templates/posts/test.html
You're viewing {{ id }}